stages:
  - install
  - test
  - build
  - deploy:dev
  - deploy:prod

install_dependencies:
  stage: install
  image: node  
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

make_pretty:
  stage: test
  image: node  
  script:
    - npm run lint

test_server:
  stage: test
  image: node  
  script:
    - npm run test

build:
  stage: build
  image: node  
  script:
    - npm run build
  artifacts:
    paths:
      - public/

deploy_dev:
  stage: deploy:dev
  image: ruby
  script:
    - gem install dpl
    - dpl --provider=heroku --app=devconzorkingkongclock --api-key=$HEROKU_KEY
  only:
    - development
