stages:
  - install
  - test
  - build
  - register:prod
  - deploy:dev
  - deploy:prod

install_dependencies:
  stage: install
  image: node  
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

make_pretty:
  stage: test
  image: node  
  script:
    - npm run lint

build:
  stage: build
  image: node  
  script:
    - npm run build
  artifacts:
    paths:
      - public/

register_container_prod:
  stage: register:prod
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u conzorkingkong -p $PASSWORD registry.gitlab.com
    - docker build -t --build-arg API_URL=$API_URL registry.gitlab.com/conzorkingkong/clock .
    - docker push registry.gitlab.com/conzorkingkong/clock:latest