image: node

before_script:
  - npm install

stages:
  - build
  - test
  - lint

install_dependencies:
  stage: build
  script:
    - npm run build

test_server:
  stage: test
  script:
    - npm run test

make_pretty:
  stage: lint
  script:
    - npm run lint
