version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    ports:
      - "3000:80"
  frontend:
    build:
      context: .
    expose:
      - "3000"
  backend:
    depends_on:
      - mongo
    image: registry.gitlab.com/conzorkingkong/clock-backend
    expose:
      - "3000"
  mongo:
    container_name: mongo
    image: mongo:3.5
    ports:
      - '27017:27017'