version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    ports:
      - "3000:80"
  frontend:
    build:
      context: .
    expose:
      - "3000"
  backend:
    image: clockback
    expose:
      - "3000"